spring:
  application:
    name: bookspot

  datasource:
    url: jdbc:postgresql://localhost:5432/BookSpot
    username: postgis
    password: postgis
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    ignore-migration-patterns: "*:ignored"
    baseline-on-migrate: true